/*
 * $RCSfile: FinderTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.ConfigFactory;
import com.skin.finder.i18n.I18N;
import com.skin.finder.i18n.LocalizationContext;


/**
 * <p>Title: FinderTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class FinderTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final FinderTemplate instance = new FinderTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        PrintWriter out = response.getWriter();


    LocalizationContext i18n = I18N.getBundle(request);

        out.write("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
        out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
        out.write("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - ");
        this.print(out, request.getAttribute("path"));
        out.write("</title>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/css/finder.css\"/>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/ajax.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/widget.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/fileupload.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/finder.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/plugins.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/lang/");
        this.print(out, (i18n.getLang()));
        out.write(".js\"></script>\r\n</head>\r\n<body localIp=\"");
        this.print(out, request.getAttribute("localIp"));
        out.write("\" contextPath=\"");
        this.print(out, request.getAttribute("contextPath"));
        out.write("\" host=\"");
        this.print(out, request.getAttribute("host"));
        out.write("\" workspace=\"");
        this.print(out, request.getAttribute("workspace"));
        out.write("\" work=\"");
        this.print(out, request.getAttribute("work"));
        out.write("\" parent=\"");
        this.print(out, request.getAttribute("parent"));
        out.write("\" path=\"");
        this.print(out, request.getAttribute("path"));
        out.write("\">\r\n<div class=\"finder\" style=\"min-width: 960px;\">\r\n    <div class=\"menu-bar\" contextmenu=\"false\">\r\n");
        out.write("        <div style=\"float: left; width: 80px;\">\r\n            <a id=\"back\" class=\"button\" href=\"javascript:void(0)\" title=\"");
        this.print(out, (i18n.getString("finder.button.back")));
        out.write("\"><span class=\"back\"></span></a>\r\n            <a id=\"refresh\" class=\"button\" href=\"javascript:void(0)\" title=\"");
        this.print(out, (i18n.getString("finder.button.refresh")));
        out.write("\"><span class=\"refresh\"></span></a>\r\n        </div>\r\n        <div style=\"float: left; height: 28px; position: relative;\">\r\n");
        out.write("            <div style=\"float: left;\"><input id=\"address\" type=\"text\" class=\"address\" autocomplete=\"off\" spellcheck=\"false\" value=\"");
        this.print(out, request.getAttribute("path"));
        out.write("\"/></div>\r\n            <div id=\"finder-suggest\" class=\"suggest\"></div>\r\n            <a class=\"button\" href=\"javascript:void(0)\" title=\"");
        this.print(out, (i18n.getString("finder.list.view.thumbnail")));
        out.write("\"><span class=\"view\"></span></a>\r\n            <div id=\"view-options\" class=\"list view-menu\">\r\n");
        out.write("                <ul>\r\n                    <li index=\"0\" option-value=\"outline\"><a href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.list.view.thumbnail")));
        out.write("</a></li>\r\n                    <li index=\"1\" option-value=\"detail\" class=\"selected\"><a href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.list.view.detail")));
        out.write("</a></li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n        <div style=\"float: right; width: 120px;\">\r\n");
        out.write("            <a class=\"button home\" href=\"javascript:void(0)\" title=\"");
        this.print(out, (i18n.getString("finder.index.home")));
        out.write("\"><span class=\"home\"></span></a>\r\n            <a class=\"button setting\" href=\"javascript:void(0)\" title=\"");
        this.print(out, (i18n.getString("finder.index.setting")));
        out.write("\"><span class=\"setting\"></span></a>\r\n            <a class=\"button help\" href=\"javascript:void(0)\" title=\"");
        this.print(out, (i18n.getString("finder.index.help")));
        out.write("\" target=\"_blank\"><span class=\"help\"></span></a>\r\n        </div>\r\n    </div>\r\n    <div id=\"file-view\" class=\"detail-view\">\r\n");
        out.write("        <div id=\"head-view\" class=\"head\">\r\n            <span class=\"icon\">&nbsp;</span>\r\n");
        out.write("            <span class=\"fileName orderable\" orderBy=\"file-name\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.file-name")));
        out.write("</em><em class=\"order asc\"></em></span>\r\n            <span class=\"fileSize orderable\" orderBy=\"file-size\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.file-size")));
        out.write("</em><em class=\"order\"></em></span>\r\n            <span class=\"fileType orderable\" orderBy=\"file-type\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.file-type")));
        out.write("</em><em class=\"order\"></em></span>\r\n            <span class=\"lastModified orderable\" orderBy=\"last-modified\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.last-modified")));
        out.write("</em><em class=\"order\"></em></span>\r\n            <span class=\"operate\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.operate")));
        out.write("</em></span>\r\n        </div>\r\n        <ul id=\"file-list\" class=\"file-list\" style=\"-moz-user-select:none; -webkit-user-select:none; user-select:none;\" onselectstart=\"return false;\"></ul>\r\n");
        out.write("    </div>\r\n</div>\r\n<div id=\"finder-contextmenu\" class=\"contextmenu\" style=\"top: 50px; left: 100px; display: none;\">\r\n");
        out.write("    <ul class=\"menu\">\r\n        <li class=\"item\" command=\"open\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"></span>\r\n            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.open")));
        out.write("(O)</a>\r\n        </li>\r\n        <li class=\"item\" command=\"upload\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/upload.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.upload")));
        out.write("(F)</a>\r\n        </li>\r\n        <li class=\"item disabled\" command=\"download\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/download.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.download")));
        out.write("(G)</a>\r\n        </li>\r\n        <li class=\"separator\"></li>\r\n        <li class=\"item disabled\" command=\"cut\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/cut.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.cut")));
        out.write("(X)</a>\r\n        </li>\r\n        <li class=\"item disabled\" command=\"copy\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/copy.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.copy")));
        out.write("(C)</a>\r\n        </li>\r\n        <li class=\"item disabled\" command=\"paste\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/paste.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.paste")));
        out.write("(V)</a>\r\n        </li>\r\n        <li class=\"separator\"></li>\r\n        <li class=\"item disabled\" command=\"remove\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/delete.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.delete")));
        out.write("(D)</a>\r\n        </li>\r\n        <li class=\"separator\"></li>\r\n        <li class=\"item\" command=\"rename\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"></span>\r\n            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.rename")));
        out.write("(F2)</a>\r\n        </li>\r\n        <li class=\"item\" command=\"mkdir\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/folder.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.mkdir")));
        out.write("(N)</a>\r\n        </li>\r\n        <li class=\"item\" command=\"refresh\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/refresh.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.refresh")));
        out.write("(E)</a>\r\n        </li>\r\n        <li class=\"separator\"></li>\r\n        <li class=\"item\" command=\"help\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\" style=\"padding-left: 6px; width: 34px; line-height: 22px;\"><img src=\"?action=res&path=/finder/images/help.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.help")));
        out.write("(H)</a>\r\n        </li>\r\n        <li class=\"item\" command=\"info\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/props.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.info")));
        out.write("(R)</a>\r\n        </li>\r\n        <li class=\"separator\"></li>\r\n        <li class=\"item disabled\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"></span>\r\n            <a class=\"command\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.context-menu.browser")));
        out.write("</a>\r\n        </li>\r\n    </ul>\r\n</div>\r\n<div id=\"finder-properties\" class=\"dialog props-dialog\" contextmenu=\"false\">\r\n");
        out.write("    <div class=\"title\">\r\n        <h4>");
        this.print(out, (i18n.getString("finder.dialog.props.title")));
        out.write("</h4>\r\n        <span class=\"close\" dragable=\"false\"></span>\r\n    </div>\r\n    <div class=\"body\">\r\n");
        out.write("        <div style=\"padding: 20px 8px 8px 20px;\">\r\n            <div class=\"cp-file-name\">\r\n");
        out.write("                <span class=\"label\"><img src=\"\" class=\"file-icon\"/></span>\r\n                <input name=\"fileName\" type=\"text\" class=\"file-name\" spellcheck=\"false\" value=\"\"/>\r\n");
        out.write("            </div>\r\n            <div class=\"separator\"></div>\r\n            <div class=\"cp-file-type\">\r\n");
        out.write("                <span class=\"label\">");
        this.print(out, (i18n.getString("finder.dialog.props.type")));
        out.write(":</span>\r\n                <span class=\"field\">&nbsp;</span>\r\n            </div>\r\n");
        out.write("            <div class=\"cp-file-path\">\r\n                <span class=\"label\">");
        this.print(out, (i18n.getString("finder.dialog.props.path")));
        out.write(":</span>\r\n                <span class=\"field\">&nbsp;</span>\r\n            </div>\r\n");
        out.write("            <div class=\"cp-file-size\">\r\n                <span class=\"label\">");
        this.print(out, (i18n.getString("finder.dialog.props.size")));
        out.write(":</span>\r\n                <span class=\"field\">&nbsp;</span>\r\n            </div>\r\n");
        out.write("            <div class=\"cp-file-modified\">\r\n                <span class=\"label\">");
        this.print(out, (i18n.getString("finder.dialog.props.last-modified")));
        out.write(":</span>\r\n                <span class=\"field\">&nbsp;</span>\r\n            </div>\r\n");
        out.write("            <div class=\"separator\"></div>\r\n        </div>\r\n    </div>\r\n    <div class=\"button right\">\r\n");
        out.write("        <button type=\"button\" class=\"button ensure\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.dialog.button.ensure")));
        out.write("</button>\r\n        <button type=\"button\" class=\"button cancel\" href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.dialog.button.cancel")));
        out.write("</button>\r\n    </div>\r\n</div>\r\n<div id=\"finder-imageviewer\" class=\"dialog\" style=\"top: 0px; width: 800px; height: 600px; display: none;\" contextmenu=\"false\">\r\n");
        out.write("    <div class=\"title\">\r\n        <h4>");
        this.print(out, (i18n.getString("finder.dialog.image.title")));
        out.write("</h4>\r\n        <span class=\"close\" dragable=\"false\"></span>\r\n    </div>\r\n    <div class=\"body\">\r\n");
        out.write("        <div style=\"margin-top: 20px; height: 440px; border: 0px solid #dddddd; line-height: 420px; text-align: center; overflow: hidden;\">\r\n");
        out.write("            <img id=\"finder_imgviewer_img\" src=\"?action=res&path=/finder/images/loading.gif\" style=\"vertical-align: middle;\"/>\r\n");
        out.write("        </div>\r\n        <div style=\"margin: 20px 0px 10px 0px; text-align: center; color: #666666;\">\r\n");
        out.write("            <a id=\"finder_imgviewer_url\" style=\"font-size: 12px;\" href=\"javascript:void(0)\" target=\"_blank\">");
        this.print(out, (i18n.getString("finder.dialog.image.view-picture")));
        out.write("</a>\r\n        </div>\r\n        <div style=\"width: 110px; margin: 0px auto 0px auto; overflow: hidden;\">\r\n");
        out.write("            <div class=\"pagebar\">\r\n                <a class=\"page active prev\" href=\"javascript:void(0)\" title=\"");
        this.print(out, (i18n.getString("finder.dialog.image.button.prev")));
        out.write("\"><span class=\"prev\"></span></a>\r\n                <span style=\"float: left; display: inline-block; width: 30px;\">&nbsp;</span>\r\n");
        out.write("                <a class=\"next active page\" href=\"javascript:void(0)\" title=\"");
        this.print(out, (i18n.getString("finder.dialog.image.button.next")));
        out.write("\"><span class=\"next\"></span></a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");
        out.write("</div>\r\n<div id=\"loading\" class=\"widget-mask\" style=\"display: block;\" contextmenu=\"false\"><div class=\"loading\"><img src=\"?action=res&path=/finder/images/loading.gif\"/></div></div>\r\n");
        out.write("<div id=\"pageContext\" style=\"display: none;\" upload-part-size=\"");
        this.print(out, (ConfigFactory.getString("finder.upload.part-size", "5M")));
        out.write("\" display-operate-button=\"");
        this.print(out, (ConfigFactory.getString("finder.display.operate-button")));
        out.write("\"></div>\r\n</body>\r\n</html>\r\n");

        out.flush();
    }


}
