/*
 * $RCSfile: FinderBakTemplate.java,v $
 * $Revision: 1.1 $
 * $Date: 2017-08-05 $
 *
 * JSP generated by JspCompiler-1.0.0 (built 2017-08-05 00:43:18 518)
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.List;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import com.skin.finder.FileItem;
import com.skin.finder.config.ConfigFactory;
import com.skin.finder.i18n.I18N;
import com.skin.finder.i18n.LocalizationContext;


/**
 * <p>Title: FinderBakTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class FinderBakTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final FinderBakTemplate instance = new FinderBakTemplate();


    private String getFileSize(long size) {
        if(size < 1024) {
            return size + " B";
        }

        if(size < 1048576) {
            return (size / 1024) + "KB";
        }

        DecimalFormat decimalFormat = new DecimalFormat("0.00");

        if(size < 1073741824) {
            return decimalFormat.format(size / 1048576.0f) + "MB";
        }
        return decimalFormat.format(size / 1073741824.0f) + "GB";
    }


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        PrintWriter out = response.getWriter();


    LocalizationContext i18n = I18N.getBundle(request);

        out.write("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
        out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
        out.write("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - ");
        this.print(out, request.getAttribute("path"));
        out.write("</title>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/css/finder.css\"/>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/ajax.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/widget.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/fileupload.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/finder.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/plugins.js\"></script>\r\n</head>\r\n<body localIp=\"");
        this.print(out, request.getAttribute("localIp"));
        out.write("\" contextPath=\"");
        this.print(out, request.getAttribute("contextPath"));
        out.write("\" workspace=\"");
        this.print(out, request.getAttribute("workspace"));
        out.write("\" work=\"");
        this.print(out, request.getAttribute("work"));
        out.write("\" parent=\"");
        this.print(out, request.getAttribute("parent"));
        out.write("\" path=\"");
        this.print(out, request.getAttribute("path"));
        out.write("\">\r\n<div class=\"finder\" style=\"min-width: 960px;\">\r\n    <div class=\"menu-bar\" contextmenu=\"false\">\r\n");
        out.write("        <div style=\"float: left; width: 80px;\">\r\n            <a id=\"back\" class=\"button\" href=\"javascript:void(0)\" title=\"后退\"><span class=\"back\"></span></a>\r\n");
        out.write("            <a id=\"refresh\" class=\"button\" href=\"javascript:void(0)\" title=\"刷新\"><span class=\"refresh\"></span></a>\r\n");
        out.write("        </div>\r\n        <div style=\"float: left; height: 28px; position: relative;\">\r\n");
        out.write("            <div style=\"float: left;\"><input id=\"address\" type=\"text\" class=\"address\" autocomplete=\"off\" value=\"");
        this.print(out, request.getAttribute("path"));
        out.write("\"/></div>\r\n            <div id=\"finder-suggest\" class=\"list suggest\"></div>\r\n            <a class=\"button\" href=\"javascript:void(0)\" title=\"缩略图\"><span class=\"view\"></span></a>\r\n");
        out.write("            <div id=\"view-options\" class=\"list view-menu\">\r\n                <ul>\r\n");
        out.write("                    <li index=\"0\" option-value=\"outline\"><a href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.list.view.thumbnail")));
        out.write("</a></li>\r\n                    <li index=\"1\" option-value=\"detail\" class=\"selected\"><a href=\"javascript:void(0)\">");
        this.print(out, (i18n.getString("finder.list.view.detail")));
        out.write("</a></li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n        <div style=\"float: right; width: 120px;\">\r\n");
        out.write("            <a class=\"button home\" href=\"javascript:void(0)\" title=\"首页\"><span class=\"home\"></span></a>\r\n");
        out.write("            <a class=\"button setting\" href=\"javascript:void(0)\" title=\"设置\"><span class=\"setting\"></span></a>\r\n");
        out.write("            <a class=\"button help\" href=\"javascript:void(0)\" title=\"帮助\" target=\"_blank\"><span class=\"help\"></span></a>\r\n");
        out.write("        </div>\r\n    </div>\r\n    <div id=\"file-view\" class=\"detail-view\">\r\n        <div id=\"head-view\" class=\"head\">\r\n");
        out.write("            <span class=\"icon\">&nbsp;</span>\r\n            <span class=\"fileName orderable\" orderBy=\"file-name\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.file-name")));
        out.write("</em><em class=\"order asc\"></em></span>\r\n            <span class=\"fileSize orderable\" orderBy=\"file-size\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.file-size")));
        out.write("</em><em class=\"order\"></em></span>\r\n            <span class=\"fileType orderable\" orderBy=\"file-type\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.file-type")));
        out.write("</em><em class=\"order\"></em></span>\r\n            <span class=\"lastModified orderable\" orderBy=\"last-modified\" unselectable=\"on\" onselectstart=\"return false;\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.last-modified")));
        out.write("</em><em class=\"order\"></em></span>\r\n            <span class=\"operate\"><em class=\"title\">");
        this.print(out, (i18n.getString("finder.list.title.operate")));
        out.write("</em></span>\r\n        </div>\r\n        <ul id=\"file-list\" class=\"file-list\" style=\"-moz-user-select:none; -webkit-user-select:none; user-select:none;\" onselectstart=\"return false;\">\r\n");
        out.write("        ");

            @SuppressWarnings("unchecked")
            List<FileItem> fileList = (List<FileItem>)(request.getAttribute("fileList"));

            if(fileList != null) {
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

                for(FileItem fileItem : fileList) {
                    if(fileItem.getIsFile()) {
                        continue;
                    }
        
        out.write("\r\n            <li class=\"item\" isFile=\"false\" fileName=\"");
        this.print(out, (fileItem.getFileName()));
        out.write("\" lastModified=\"");
        this.print(out, (fileItem.getLastModified()));
        out.write("\">\r\n                <span class=\"icon\"><img src=\"?action=res&path=/finder/images/folder.gif\"/></span>\r\n");
        out.write("                <span class=\"fileName\"><a class=\"file\" href=\"javascript:void(0)\" bind-event=\"dblclick\">");
        this.print(out, (fileItem.getFileName()));
        out.write("</a></span>\r\n                <span class=\"fileSize\">&nbsp;</span>\r\n                <span class=\"fileType\">文件夹</span>\r\n");
        out.write("                <span class=\"lastModified\">");
        this.print(out, (dateFormat.format(new java.util.Date(fileItem.getLastModified()))));
        out.write("</span>\r\n                <span class=\"operate\">\r\n                    <a action=\"finder-open\" href=\"javascript:void(0)\">open</a>\r\n");
        out.write("                    <a action=\"finder-remove\" href=\"javascript:void(0)\">delete</a>\r\n");
        out.write("                </span>\r\n            </li>\r\n        ");

                }

                for(FileItem fileItem : fileList) {
                    if(!fileItem.getIsFile()) {
                        continue;
                    }
        
        out.write("            <li class=\"item\" fileIcon=\"");
        this.print(out, (fileItem.getFileIcon()));
        out.write("\" fileName=\"");
        this.print(out, (fileItem.getFileName()));
        out.write("\" fileSize=\"");
        this.print(out, (fileItem.getFileSize()));
        out.write("\" lastModified=\"");
        this.print(out, (fileItem.getLastModified()));
        out.write("\">\r\n                <span class=\"icon\"><img src=\"?action=res&path=/finder/type/");
        this.print(out, (fileItem.getFileIcon()));
        out.write(".gif\"/></span>\r\n                <span class=\"fileName\"><a class=\"file\" href=\"javascript:void(0)\" bind-event=\"dblclick\">");
        this.print(out, (fileItem.getFileName()));
        out.write("</a></span>\r\n                <span class=\"fileSize\">");
        this.print(out, (this.getFileSize(fileItem.getFileSize())));
        out.write("</span>\r\n                <span class=\"fileType\">");
        this.print(out, (fileItem.getFileType()));
        out.write("文件</span>\r\n                <span class=\"lastModified\">");
        this.print(out, (dateFormat.format(new java.util.Date(fileItem.getLastModified()))));
        out.write("</span>\r\n                <span class=\"operate\">\r\n                    <a action=\"finder-tail\" href=\"javascript:void(0)\">tail</a>\r\n");
        out.write("                    <a action=\"finder-less\" href=\"javascript:void(0)\">less</a>\r\n");
        out.write("                    <a action=\"finder-grep\" href=\"javascript:void(0)\">grep</a>\r\n");
        out.write("                    <a action=\"finder-open\" href=\"javascript:void(0)\">open</a>\r\n");
        out.write("                    <a action=\"finder-download\" href=\"javascript:void(0)\">download</a>\r\n");
        out.write("                    <a action=\"finder-remove\" href=\"javascript:void(0)\">delete</a>\r\n");
        out.write("                </span>\r\n            </li>\r\n        ");

                }
            }
        
        out.write("        </ul>\r\n    </div>\r\n</div>\r\n<div id=\"finder-contextmenu\" class=\"contextmenu\" style=\"top: 50px; left: 100px; display: none;\">\r\n");
        out.write("    <ul class=\"menu\">\r\n        <li class=\"item\" command=\"open\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"></span>\r\n            <a class=\"command\" href=\"javascript:void(0)\">打 开(O)</a>\r\n");
        out.write("        </li>\r\n        <li class=\"item\" command=\"upload\" unselectable=\"on\">\r\n            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/upload.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">上 传(F)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"item disabled\" command=\"download\" unselectable=\"on\">\r\n            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/download.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">下 载(G)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"separator\"></li>\r\n        <li class=\"item disabled\" command=\"cut\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/cut.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">剪 切(X)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"item disabled\" command=\"copy\" unselectable=\"on\">\r\n            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/copy.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">复 制(C)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"item disabled\" command=\"paste\" unselectable=\"on\">\r\n            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/paste.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">粘 贴(V)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"separator\"></li>\r\n        <li class=\"item disabled\" command=\"remove\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/delete.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">删 除(D)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"separator\"></li>\r\n        <li class=\"item\" command=\"rename\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"></span>\r\n            <a class=\"command\" href=\"javascript:void(0)\">重命名(F2)</a>\r\n");
        out.write("        </li>\r\n        <li class=\"item\" command=\"mkdir\" unselectable=\"on\">\r\n            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/folder.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">新建文件夹(N)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"item\" command=\"refresh\" unselectable=\"on\">\r\n            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/refresh.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">刷 新(E)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"separator\"></li>\r\n        <li class=\"item\" command=\"help\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\" style=\"padding-left: 6px; width: 34px; line-height: 22px;\"><img src=\"?action=res&path=/finder/images/help.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">帮 助(H)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"item\" command=\"info\" unselectable=\"on\">\r\n            <span class=\"icon\"><img src=\"?action=res&path=/finder/images/props.gif\"/></span>\r\n");
        out.write("            <a class=\"command\" href=\"javascript:void(0)\">属 性(R)</a>\r\n        </li>\r\n");
        out.write("        <li class=\"separator\"></li>\r\n        <li class=\"item disabled\" unselectable=\"on\">\r\n");
        out.write("            <span class=\"icon\"></span>\r\n            <a class=\"command\" href=\"javascript:void(0)\">浏览器菜单: ctrl+右键</a>\r\n");
        out.write("        </li>\r\n    </ul>\r\n</div>\r\n\r\n<div id=\"finder-properties\" class=\"dialog props-dialog\" contextmenu=\"false\">\r\n");
        out.write("    <div class=\"title\">\r\n        <h4>属性对话框</h4>\r\n        <span class=\"close\" dragable=\"false\"></span>\r\n");
        out.write("    </div>\r\n    <div class=\"body\">\r\n        <div style=\"padding: 20px 8px 8px 20px;\">\r\n");
        out.write("            <div class=\"cp-file-name\">\r\n                <span class=\"label\"><img src=\"\" class=\"file-icon\"/></span>\r\n");
        out.write("                <input name=\"fileName\" type=\"text\" class=\"file-name\" value=\"\"/>\r\n");
        out.write("            </div>\r\n            <div class=\"separator\"></div>\r\n            <div class=\"cp-file-type\">\r\n");
        out.write("                <span class=\"label\">类型：</span>\r\n                <span class=\"field\">&nbsp;</span>\r\n");
        out.write("            </div>\r\n            <div class=\"cp-file-path\">\r\n                <span class=\"label\">位置：</span>\r\n");
        out.write("                <span class=\"field\">&nbsp;</span>\r\n            </div>\r\n            <div class=\"cp-file-size\">\r\n");
        out.write("                <span class=\"label\">大小：</span>\r\n                <span class=\"field\">&nbsp;</span>\r\n");
        out.write("            </div>\r\n            <div class=\"cp-file-modified\">\r\n                <span class=\"label\">修改时间：</span>\r\n");
        out.write("                <span class=\"field\">&nbsp;</span>\r\n            </div>\r\n            <div class=\"separator\"></div>\r\n");
        out.write("        </div>\r\n    </div>\r\n    <div class=\"button right\">\r\n        <button type=\"button\" class=\"button ensure\" href=\"javascript:void(0)\">确 定</button>\r\n");
        out.write("        <button type=\"button\" class=\"button cancel\" href=\"javascript:void(0)\">取 消</button>\r\n");
        out.write("    </div>\r\n</div>\r\n\r\n<div id=\"finder-imageviewer\" class=\"dialog\" style=\"top: 0px; width: 800px; height: 600px; display: none;\" contextmenu=\"false\">\r\n");
        out.write("    <div class=\"title\">\r\n        <h4>Finder Image Viewer</h4>\r\n        <span class=\"close\" dragable=\"false\"></span>\r\n");
        out.write("    </div>\r\n    <div class=\"body\">\r\n        <div style=\"margin-top: 20px; height: 440px; border: 0px solid #dddddd; line-height: 420px; text-align: center; overflow: hidden;\">\r\n");
        out.write("            <img id=\"finder_imgviewer_img\" src=\"?action=res&path=/finder/images/hua.jpg\" style=\"vertical-align: middle;\"/>\r\n");
        out.write("        </div>\r\n        <div style=\"margin: 20px 0px 10px 0px; text-align: center; color: #666666;\">\r\n");
        out.write("            <a id=\"finder_imgviewer_url\" style=\"font-size: 12px;\" href=\"javascript:void(0)\" target=\"_blank\">查看原图</a>\r\n");
        out.write("        </div>\r\n        <div style=\"width: 110px; margin: 0px auto 0px auto; overflow: hidden;\">\r\n");
        out.write("            <div class=\"pagebar\">\r\n                <a class=\"page active prev\" href=\"javascript:void(0)\" title=\"上一张\"><span class=\"prev\"></span></a>\r\n");
        out.write("                <span style=\"float: left; display: inline-block; width: 30px;\">&nbsp;</span>\r\n");
        out.write("                <a class=\"next active page\" href=\"javascript:void(0)\" title=\"下一张\"><span class=\"next\"></span></a>\r\n");
        out.write("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" upload-part-size=\"");
        this.print(out, (ConfigFactory.getString("finder.upload.part-size", "5M")));
        out.write("\"></div>\r\n</body>\r\n</html>\r\n");

        out.flush();
    }


}
