/*
 * $RCSfile: GrepTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: GrepTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class GrepTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final GrepTemplate instance = new GrepTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        PrintWriter out = response.getWriter();

        out.write("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
        out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
        out.write("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>WebGrep</title>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/css/less.css\"/>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/config.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/charset.js\"></script>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/grep.js\"></script>\r\n<script type=\"text/javascript\">\r\n<!--\r\n");
        out.write("jQuery(function() {\r\n    var container = Grep.getContainer();\r\n\r\n    jQuery(window).bind(\"resize\", function(){\r\n");
        out.write("        jQuery(container).height(jQuery(window).height() - 68);\r\n    });\r\n    jQuery(window).trigger(\"resize\");\r\n");
        out.write("});\r\n\r\njQuery(function() {\r\n    Grep.grepURL = \"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=grep.find&\";\r\n    Grep.init();\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
        this.print(out, request.getAttribute("contextPath"));
        out.write("\" host=\"");
        this.print(out, request.getAttribute("host"));
        out.write("\" workspace=\"");
        this.print(out, request.getAttribute("workspace"));
        out.write("\" parent=\"");
        this.print(out, request.getAttribute("parent"));
        out.write("\" path=\"");
        this.print(out, request.getAttribute("path"));
        out.write("\" charset=\"");
        this.print(out, request.getAttribute("charset"));
        out.write("\">\r\n<!-- 设置-语言-语言和输入设置-去掉勾选 启用拼写检查 -->\r\n<div id=\"less-container\" class=\"less-container\" contenteditable=\"true\" spellcheck=\"false\"></div>\r\n");
        out.write("<div id=\"less-progress-bar\" class=\"less-progress-bar\">\r\n    <div class=\"progress\">\r\n");
        out.write("        <div class=\"slider\">\r\n            <div class=\"pace\"></div>\r\n            <a class=\"dot\" href=\"#\"></a>\r\n");
        out.write("            <div class=\"mask\"></div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div id=\"less-status-bar\" class=\"less-status-bar\">\r\n");
        out.write("    <div style=\"height: 18px; background-color: #333333;\">\r\n        <span class=\"charset\">\r\n");
        out.write("            <select name=\"charset\" selected-value=\"");
        this.print(out, request.getAttribute("charset"));
        out.write("\"></select>\r\n        </span>\r\n        <span class=\"file\"><input id=\"less-file\" type=\"text\" class=\"text w240\" readonly=\"true\" value=\"");
        this.print(out, request.getAttribute("absolutePath"));
        out.write("\"/></span>\r\n        <span class=\"info\"><input id=\"less-info\" type=\"text\" class=\"text w160\" readonly=\"true\" value=\"0 B\"/></span>\r\n");
        out.write("        <span class=\"status\"><input id=\"less-status\" type=\"text\" class=\"text w160\" readonly=\"true\" value=\"READY\"/></span>\r\n");
        out.write("    </div>\r\n</div>\r\n<div id=\"less-tooltip\" class=\"less-tooltip\">50%</div>\r\n<div id=\"find-panel\" class=\"find-panel\">\r\n");
        out.write("    <div>\r\n        查找内容: <input id=\"grep-keyword\" type=\"text\" class=\"grep-keyword\" value=\"\" placeholder=\"正则示例: /finder/.*\\.html\"/>\r\n");
        out.write("        <input id=\"grep-ensure\" type=\"button\" class=\"grep-search\" value=\"查找\"/>\r\n");
        out.write("    </div>\r\n    <div style=\"clear: both; padding-top: 12px; height: 20px;\">\r\n        <span style=\"float: left; width: 10px; display: inline-block;\"><input id=\"grep-regexp\" type=\"checkbox\" title=\"正则表达式\"/></span>\r\n");
        out.write("        <span style=\"float: left; margin-left: 6px; margin-top: -1px; width: 100px; display: inline-block;\">正则表达式</span>\r\n");
        out.write("    </div>\r\n    <div style=\"clear: both; margin-top: 10px;\">\r\n        <p><span style=\"color: #ff0000;\">提示：</span>快捷键(Ctrl + B)，再次按下可关闭。</p>\r\n");
        out.write("        <p><span style=\"color: #ff0000;\">参考：</span><a href=\"http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#sum\" target=\"_blank\">正则表达式参考</a></p>\r\n");
        out.write("    </div>\r\n    <div style=\"text-align: center;\">\r\n        <input id=\"grep-close\" type=\"button\" class=\"grep-button\" value=\"关闭\"/>\r\n");
        out.write("    </div>\r\n</div>\r\n</body>\r\n</html>\r\n");

        out.flush();
    }


}
