/*
 * $RCSfile: HelpTemplate.java,v $
 * $Revision: 1.1 $
 * $Date: 2017-08-05 $
 *
 * JSP generated by JspCompiler-1.0.0 (built 2017-08-05 00:43:18 536)
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: HelpTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class HelpTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final HelpTemplate instance = new HelpTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        PrintWriter out = response.getWriter();

        out.write("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
        out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
        out.write("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>帮助中心</title>\r\n<style type=\"text/css\">\r\n");
        out.write("ul.list{list-style-type: disc;}\r\nul.list li{line-height: 24px; font-size: 13px;}\r\n");
        out.write("table{font-size: 13px;}\r\ntable tr td{padding-left: 4px; height: 24px; font-size: 13px;}\r\n");
        out.write("</style>\r\n</head>\r\n<body>\r\n<div class=\"finder\">\r\n    <div class=\"menu-bar\" style=\"padding-top: 4px;\">\r\n");
        out.write("        <div style=\"float: left; width: 80px;\">\r\n            <a class=\"button disabled\" href=\"javascript:void(0)\"><span class=\"back-disabled\"></span></a>\r\n");
        out.write("            <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\" title=\"刷新\"><span class=\"refresh\"></span></a>\r\n");
        out.write("        </div>\r\n        <div style=\"float: left; height: 28px; position: relative;\"></div>\r\n");
        out.write("        <div style=\"float: right; width: 40px;\">\r\n            <a class=\"button\" href=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=finder.help\" title=\"帮助\"><span class=\"help\"></span></a>\r\n        </div>\r\n");
        out.write("    </div>\r\n</div>\r\n\r\n<div class=\"finder\">\r\n    <h1>功能</h1>\r\n    <ul class=\"list\">\r\n");
        out.write("        <li>Finder是一个模拟windows资源浏览器的web文件管理工具。</li>\r\n        <li>支持全键盘操作，几乎所有操作均有对应的快捷键支持。</li>\r\n");
        out.write("        <li>支持右键菜单，文件的常规操作都可以通过右键菜单完成。</li>\r\n        <li>支持文件重命名，点击选中文件，然后按F2即可重命名文件。</li>\r\n");
        out.write("        <li>支持大上传，超大文件会自动分段上传，默认设置每次上传10M。</li>\r\n        <li>支持文件拖拽上传，可同时拖拽多个文件上传。</li>\r\n");
        out.write("        <li>支持截图上传，截图之后按Ctrl + V。</li>\r\n        <li>grep支持，类似linux系统的grep命令，支持任意大小的文件。</li>\r\n");
        out.write("        <li>less支持，类似linux系统的less命令，支持任意大小的文件。</li>\r\n        <li>tail支持，类似linux系统的tail命令，支持任意大小的文件。</li>\r\n");
        out.write("    </ul>\r\n</div>\r\n\r\n<div class=\"finder\">\r\n    <h1>使用技巧</h1>\r\n    <ul class=\"list\">\r\n");
        out.write("        <li>双击文件名可以打开文件。</li>\r\n        <li>按住Ctrl键可以在新窗口打开less和tail。</li>\r\n        <li>音频播放的同时可以继续其他操作，包括切换不同的文件夹。</li>\r\n");
        out.write("        <li>地址栏的suggest列表也是支持键盘上下键滚动的哦。</li>\r\n    </ul>\r\n</div>\r\n\r\n<div class=\"finder\">\r\n");
        out.write("    <h1>快捷键</h1>\r\n    <table>\r\n        <tr>\r\n            <td style=\"width: 480px; height: 30px; background-color: #efefef;\">操作</td>\r\n");
        out.write("            <td style=\"width: 300px; height: 30px; background-color: #efefef;\">快捷键</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>重命名</td>\r\n            <td>F2</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>向上滚动</td>\r\n            <td>UP</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>向下滚动</td>\r\n            <td>DOWN</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>向左滚动</td>\r\n            <td>LEFT</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>向右滚动</td>\r\n            <td>RIGHT</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>全选</td>\r\n            <td>CTRL + A</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>剪切</td>\r\n            <td>CTRL + X</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>拷贝</td>\r\n            <td>CTRL + C</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>粘贴</td>\r\n            <td>CTRL + V</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>多选</td>\r\n            <td>CTRL + CLICK</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>多选</td>\r\n            <td>ALT + CLICK</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>多选</td>\r\n            <td>CTRL + [UP|DOWN|LEFT|RIGHT]</td>\r\n");
        out.write("        </tr>\r\n        <tr>\r\n            <td>删除选中文件</td>\r\n            <td>DELETE</td>\r\n");
        out.write("        </tr>\r\n    </table>\r\n</div>\r\n<div class=\"h20\"></div>\r\n</body>\r\n</html>\r\n");

        out.flush();
    }


}
