/*
 * $RCSfile: LoginTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: LoginTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class LoginTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final LoginTemplate instance = new LoginTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        PrintWriter out = response.getWriter();

        out.write("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
        out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
        out.write("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Login</title>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/css/user.css\"/>\r\n<script type=\"text/javascript\" src=\"");
        this.print(out, request.getAttribute("requestURI"));
        out.write("?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n<script type=\"text/javascript\">\r\n");
        out.write("<!--\r\njQuery(function() {\r\n    jQuery(\"#submit\").click(function() {\r\n        var userName = jQuery.trim(jQuery(\"#s1\").val());\r\n");
        out.write("        var password = jQuery.trim(jQuery(\"#s2\").val());\r\n        var params = \"userName=\" + encodeURIComponent(userName) + \"&password=\" + encodeURIComponent(password);\r\n");
        out.write("        var requestURI = window.location.pathname;\r\n\r\n        jQuery.ajax({\r\n            type: \"post\",\r\n");
        out.write("            url: requestURI + \"?action=finder.login\",\r\n            dataType: \"json\",\r\n");
        out.write("            data: params,\r\n            error: function(req, status, error) {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
        out.write("            },\r\n            success: function(result) {\r\n                if(result.status == 200) {\r\n");
        out.write("                    window.location.href = \"");
        this.print(out, request.getAttribute("contextPath"));
        out.write("/index.html\";\r\n                }\r\n                else {\r\n                    alert(result.message);\r\n");
        out.write("                }\r\n            }\r\n        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n");
        out.write("<body>\r\n<div class=\"wrap\">\r\n    <div class=\"login-container\">\r\n        <h3>登录</h3>\r\n");
        out.write("        <div class=\"login-panel\">\r\n            <div class=\"row\"><input id=\"s1\" type=\"text\" class=\"text\" spellcheck=\"false\" placeholder=\"UserName\" value=\"\"/></div>\r\n");
        out.write("            <div class=\"row\"><input id=\"s2\" type=\"password\" class=\"text\" placeholder=\"Password\" value=\"\"/></div>\r\n");
        out.write("            <div class=\"row\"><input id=\"submit\" type=\"button\" class=\"button\" value=\"登录\"/></div>\r\n");
        out.write("        </div>\r\n    </div>\r\n</div>\r\n</body>\r\n</html>\r\n");

        out.flush();
    }


}
