/*
 * $RCSfile: ${java.className}.java,v $
 * $Revision: 1.1 $
 * $Date: ${build.date} $
 *
 * JSP generated by JspCompiler-${compiler.version} (built ${build.time})
 */
package ${java.packageName};

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

${jsp.directive.import}

/**
 * <p>Title: ${java.className}</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class ${java.className} extends ${java.super.className} {
    private static final long serialVersionUID = 1L;
    private static final ${java.className} instance = new ${java.className}();

${jsp.declaration}
    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        PrintWriter out = response.getWriter();

${jsp.method.body}
        out.flush();
    }
${jsp.subclass.body}
${jsp.static.declaration}
}
